spring:
  jpa:
    generate-ddl: true
  datasource:
  url: jdbc:postgresql://localhost:5432/app_db
  username: postgres
  password: postgres
  hikari:
    schema: app_schema
    connection-ini-sql: CREATE SCHEMA IF NOT EXiSTS app_schema
    connection-timeout: 10000

app:
  integration:
    base-url: http://localhost:8082
  cache:
    cacheType: inMemory
    cache-name:
      - databaseEntities
      - databaseEntityByName
    caches:
      databaseEntities:
        expiry: 10s
      databaseEntityByName:
        expiry: 10s